package com.expenso.app.ui.theme

import androidx.compose.ui.graphics.Color

// --- COSMIC SLATE PALETTE ---
// Light Cosmic Slate
val CosmicSlateBackgroundLight = Color(0xFFF4F7FB)
val CosmicSlateTextLight = Color(0xFF101D2D)
val CosmicSlatePrimaryLight = Color(0xFF005FAF)
val CosmicSlateOnPrimaryLight = Color(0xFFFFFFFF)
val CosmicSlatePrimaryContainerLight = Color(0xFFD1E4FF)
val CosmicSlateOnPrimaryContainerLight = Color(0xFF001D36)
val CosmicSlateSecondaryLight = Color(0xFF3E8EBA)
val CosmicSlateSecondaryContainerLight = Color(0xFFDFE3EB)
val CosmicSlateOnSecondaryContainerLight = Color(0xFF141C25)
val CosmicSlateSurfaceLight = Color(0xFFFFFFFF)
val CosmicSlateOnSurfaceLight = Color(0xFF101D2D)
val CosmicSlateOutlineLight = Color(0xFF727782)
val CosmicSlateOutlineVariantLight = Color(0xFFC2C7D0)

// Dark Cosmic Slate
val CosmicSlateBackgroundDark = Color(0xFF2D3748)
val CosmicSlateTextDark = Color(0xFFF8FAFC)
val CosmicSlatePrimaryDark = Color(0xFF60A5FA)
val CosmicSlateOnPrimaryDark = Color(0xFFFFFFFF)
val CosmicSlatePrimaryContainerDark = Color(0xFF4A5568)
val CosmicSlateOnPrimaryContainerDark = Color(0xFFDBEAFE)
val CosmicSlateSecondaryDark = Color(0xFF93C5FD)
val CosmicSlateSecondaryContainerDark = Color(0xFF4A5568)
val CosmicSlateOnSecondaryContainerDark = Color(0xFFF1F5F9)
val CosmicSlateSurfaceDark = Color(0xFF374357)
val CosmicSlateOnSurfaceDark = Color(0xFFF8FAFC)
val CosmicSlateOutlineDark = Color(0xFF94A3B8)
val CosmicSlateOutlineVariantDark = Color(0xFF64748B)

// --- FOREST EMERALD PALETTE ---
// Light Forest Emerald
val ForestEmeraldBackgroundLight = Color(0xFFF3FAF5)
val ForestEmeraldTextLight = Color(0xFF191C1A)
val ForestEmeraldPrimaryLight = Color(0xFF006D44)
val ForestEmeraldOnPrimaryLight = Color(0xFFFFFFFF)
val ForestEmeraldPrimaryContainerLight = Color(0xFF90F9BF)
val ForestEmeraldOnPrimaryContainerLight = Color(0xFF002111)
val ForestEmeraldSecondaryLight = Color(0xFF4E6356)
val ForestEmeraldSecondaryContainerLight = Color(0xFFD1E9D7)
val ForestEmeraldOnSecondaryContainerLight = Color(0xFF0C1F15)
val ForestEmeraldSurfaceLight = Color(0xFFFFFFFF)
val ForestEmeraldOnSurfaceLight = Color(0xFF191C1A)
val ForestEmeraldOutlineLight = Color(0xFF707973)
val ForestEmeraldOutlineVariantLight = Color(0xFFC0C9C2)

// Dark Forest Emerald
val ForestEmeraldBackgroundDark = Color(0xFF1E2822)
val ForestEmeraldTextDark = Color(0xFFE1E3DF)
val ForestEmeraldPrimaryDark = Color(0xFF73DCA4)
val ForestEmeraldOnPrimaryDark = Color(0xFF003820)
val ForestEmeraldPrimaryContainerDark = Color(0xFF005231)
val ForestEmeraldOnPrimaryContainerDark = Color(0xFF90F9BF)
val ForestEmeraldSecondaryDark = Color(0xFFB5CCBD)
val ForestEmeraldSecondaryContainerDark = Color(0xFF374B3F)
val ForestEmeraldOnSecondaryContainerDark = Color(0xFFD1E9D7)
val ForestEmeraldSurfaceDark = Color(0xFF242F28)
val ForestEmeraldOnSurfaceDark = Color(0xFFE1E3DF)
val ForestEmeraldOutlineDark = Color(0xFF8A938C)
val ForestEmeraldOutlineVariantDark = Color(0xFF404943)

// --- WARM TERRACOTTA PALETTE ---
// Light Warm Terracotta
val WarmTerracottaBackgroundLight = Color(0xFFFFF8F6)
val WarmTerracottaTextLight = Color(0xFF221A18)
val WarmTerracottaPrimaryLight = Color(0xFFB04A25)
val WarmTerracottaOnPrimaryLight = Color(0xFFFFFFFF)
val WarmTerracottaPrimaryContainerLight = Color(0xFFFFDBD0)
val WarmTerracottaOnPrimaryContainerLight = Color(0xFF3B0A00)
val WarmTerracottaSecondaryLight = Color(0xFF76574E)
val WarmTerracottaSecondaryContainerLight = Color(0xFFFFDBD1)
val WarmTerracottaOnSecondaryContainerLight = Color(0xFF2C1611)
val WarmTerracottaSurfaceLight = Color(0xFFFFFFFF)
val WarmTerracottaOnSurfaceLight = Color(0xFF221A18)
val WarmTerracottaOutlineLight = Color(0xFF85736E)
val WarmTerracottaOutlineVariantLight = Color(0xFFD8C2BC)

// Dark Warm Terracotta
val WarmTerracottaBackgroundDark = Color(0xFF231B19)
val WarmTerracottaTextDark = Color(0xFFEDE0DD)
val WarmTerracottaPrimaryDark = Color(0xFFFFB59E)
val WarmTerracottaOnPrimaryDark = Color(0xFF5F1C04)
val WarmTerracottaPrimaryContainerDark = Color(0xFF823214)
val WarmTerracottaOnPrimaryContainerDark = Color(0xFFFFDBD0)
val WarmTerracottaSecondaryDark = Color(0xFFE6BEB4)
val WarmTerracottaSecondaryContainerDark = Color(0xFF5C4038)
val WarmTerracottaOnSecondaryContainerDark = Color(0xFFFFDBD1)
val WarmTerracottaSurfaceDark = Color(0xFF2D2421)
val WarmTerracottaOnSurfaceDark = Color(0xFFEDE0DD)
val WarmTerracottaOutlineDark = Color(0xFFA08C87)
val WarmTerracottaOutlineVariantDark = Color(0xFF53433F)

// --- DEEP INDIGO PALETTE ---
// Light Deep Indigo
val DeepIndigoBackgroundLight = Color(0xFFFAF8FF)
val DeepIndigoTextLight = Color(0xFF1B1B21)
val DeepIndigoPrimaryLight = Color(0xFF4255A8)
val DeepIndigoOnPrimaryLight = Color(0xFFFFFFFF)
val DeepIndigoPrimaryContainerLight = Color(0xFFDEE0FF)
val DeepIndigoOnPrimaryContainerLight = Color(0xFF00104B)
val DeepIndigoSecondaryLight = Color(0xFF5B5D72)
val DeepIndigoSecondaryContainerLight = Color(0xFFE0E1F9)
val DeepIndigoOnSecondaryContainerLight = Color(0xFF181A2C)
val DeepIndigoSurfaceLight = Color(0xFFFFFFFF)
val DeepIndigoOnSurfaceLight = Color(0xFF1B1B21)
val DeepIndigoOutlineLight = Color(0xFF767680)
val DeepIndigoOutlineVariantLight = Color(0xFFC7C5D0)

// Dark Deep Indigo
val DeepIndigoBackgroundDark = Color(0xFF1D1D23)
val DeepIndigoTextDark = Color(0xFFE4E1E9)
val DeepIndigoPrimaryDark = Color(0xFFBAC3FF)
val DeepIndigoOnPrimaryDark = Color(0xFF082177)
val DeepIndigoPrimaryContainerDark = Color(0xFF283C8E)
val DeepIndigoOnPrimaryContainerDark = Color(0xFFDEE0FF)
val DeepIndigoSecondaryDark = Color(0xFFC3C5DD)
val DeepIndigoSecondaryContainerDark = Color(0xFF43455A)
val DeepIndigoOnSecondaryContainerDark = Color(0xFFE0E1F9)
val DeepIndigoSurfaceDark = Color(0xFF25252B)
val DeepIndigoOnSurfaceDark = Color(0xFFE4E1E9)
val DeepIndigoOutlineDark = Color(0xFF908F9A)
val DeepIndigoOutlineVariantDark = Color(0xFF46464F)

// --- SUNSET GOLD PALETTE ---
// Light Sunset Gold
val SunsetGoldBackgroundLight = Color(0xFFFFF9EE)
val SunsetGoldTextLight = Color(0xFF1E1A10)
val SunsetGoldPrimaryLight = Color(0xFF815500)
val SunsetGoldOnPrimaryLight = Color(0xFFFFFFFF)
val SunsetGoldPrimaryContainerLight = Color(0xFFFFDDB1)
val SunsetGoldOnPrimaryContainerLight = Color(0xFF291800)
val SunsetGoldSecondaryLight = Color(0xFF6C5D40)
val SunsetGoldSecondaryContainerLight = Color(0xFFF6E0BC)
val SunsetGoldOnSecondaryContainerLight = Color(0xFF251A04)
val SunsetGoldSurfaceLight = Color(0xFFFFFFFF)
val SunsetGoldOnSurfaceLight = Color(0xFF1E1A10)
val SunsetGoldOutlineLight = Color(0xFF817567)
val SunsetGoldOutlineVariantLight = Color(0xFFD3C4B3)

// Dark Sunset Gold
val SunsetGoldBackgroundDark = Color(0xFF1E1A13)
val SunsetGoldTextDark = Color(0xFFEBE1D4)
val SunsetGoldPrimaryDark = Color(0xFFFABB4E)
val SunsetGoldOnPrimaryDark = Color(0xFF442B00)
val SunsetGoldPrimaryContainerDark = Color(0xFF623F00)
val SunsetGoldOnPrimaryContainerDark = Color(0xFFFFDDB1)
val SunsetGoldSecondaryDark = Color(0xFFD9C4A1)
val SunsetGoldSecondaryContainerDark = Color(0xFF53452B)
val SunsetGoldOnSecondaryContainerDark = Color(0xFFF6E0BC)
val SunsetGoldSurfaceDark = Color(0xFF28241C)
val SunsetGoldOnSurfaceDark = Color(0xFFEBE1D4)
val SunsetGoldOutlineDark = Color(0xFF9B8E7F)
val SunsetGoldOutlineVariantDark = Color(0xFF4E4539)

// --- AMOLED PALETTE ---
// Light Amoled (Fallback for light mode, maybe just a very high contrast black and white)
val AmoledBackgroundLight = Color(0xFFFFFFFF)
val AmoledTextLight = Color(0xFF000000)
val AmoledPrimaryLight = Color(0xFF000000)
val AmoledOnPrimaryLight = Color(0xFFFFFFFF)
val AmoledPrimaryContainerLight = Color(0xFFE0E0E0)
val AmoledOnPrimaryContainerLight = Color(0xFF000000)
val AmoledSecondaryLight = Color(0xFF424242)
val AmoledSecondaryContainerLight = Color(0xFFEEEEEE)
val AmoledOnSecondaryContainerLight = Color(0xFF000000)
val AmoledSurfaceLight = Color(0xFFFFFFFF)
val AmoledOnSurfaceLight = Color(0xFF000000)
val AmoledOutlineLight = Color(0xFF757575)
val AmoledOutlineVariantLight = Color(0xFFE0E0E0)

// Dark Amoled (True black background)
val AmoledBackgroundDark = Color(0xFF000000)
val AmoledTextDark = Color(0xFFFFFFFF)
val AmoledPrimaryDark = Color(0xFFFFFFFF)
val AmoledOnPrimaryDark = Color(0xFF000000)
val AmoledPrimaryContainerDark = Color(0xFF222222)
val AmoledOnPrimaryContainerDark = Color(0xFFFFFFFF)
val AmoledSecondaryDark = Color(0xFFBDBDBD)
val AmoledSecondaryContainerDark = Color(0xFF111111)
val AmoledOnSecondaryContainerDark = Color(0xFFFFFFFF)
val AmoledSurfaceDark = Color(0xFF000000)
val AmoledOnSurfaceDark = Color(0xFFFFFFFF)
val AmoledOutlineDark = Color(0xFF757575)
val AmoledOutlineVariantDark = Color(0xFF333333)

// Light Lavender Dream
val LavenderDreamBackgroundLight = Color(0xFFFDF7FF)
val LavenderDreamTextLight = Color(0xFF1D1B20)
val LavenderDreamPrimaryLight = Color(0xFF6750A4)
val LavenderDreamOnPrimaryLight = Color(0xFFFFFFFF)
val LavenderDreamPrimaryContainerLight = Color(0xFFEADDFF)
val LavenderDreamOnPrimaryContainerLight = Color(0xFF21005D)
val LavenderDreamSecondaryLight = Color(0xFF625B71)
val LavenderDreamSecondaryContainerLight = Color(0xFFE8DEF8)
val LavenderDreamOnSecondaryContainerLight = Color(0xFF1D192B)
val LavenderDreamSurfaceLight = Color(0xFFFFFFFF)
val LavenderDreamOnSurfaceLight = Color(0xFF1D1B20)
val LavenderDreamOutlineLight = Color(0xFF79747E)
val LavenderDreamOutlineVariantLight = Color(0xFFCAC4D0)

// Dark Lavender Dream
val LavenderDreamBackgroundDark = Color(0xFF141218)
val LavenderDreamTextDark = Color(0xFFE6E0E9)
val LavenderDreamPrimaryDark = Color(0xFFD0BCFF)
val LavenderDreamOnPrimaryDark = Color(0xFF381E72)
val LavenderDreamPrimaryContainerDark = Color(0xFF4F378B)
val LavenderDreamOnPrimaryContainerDark = Color(0xFFEADDFF)
val LavenderDreamSecondaryDark = Color(0xFFCCC2DC)
val LavenderDreamSecondaryContainerDark = Color(0xFF4A4458)
val LavenderDreamOnSecondaryContainerDark = Color(0xFFE8DEF8)
val LavenderDreamSurfaceDark = Color(0xFF211F26)
val LavenderDreamOnSurfaceDark = Color(0xFFE6E0E9)
val LavenderDreamOutlineDark = Color(0xFF938F99)
val LavenderDreamOutlineVariantDark = Color(0xFF49454F)

// --- EXPENSO PALETTE ---
// Light Expenso
val ExpensoBackgroundLight = Color(0xFFF7F9F8)
val ExpensoTextLight = Color(0xFF1A1C1B)
val ExpensoPrimaryLight = Color(0xFF006B5D) // Deep Teal
val ExpensoOnPrimaryLight = Color(0xFFFFFFFF)
val ExpensoPrimaryContainerLight = Color(0xFF8FF5E0)
val ExpensoOnPrimaryContainerLight = Color(0xFF00201B)
val ExpensoSecondaryLight = Color(0xFF4A635E)
val ExpensoSecondaryContainerLight = Color(0xFFCCE8E2)
val ExpensoOnSecondaryContainerLight = Color(0xFF051F1B)
val ExpensoSurfaceLight = Color(0xFFFBFDF9)
val ExpensoOnSurfaceLight = Color(0xFF1A1C1B)
val ExpensoOutlineLight = Color(0xFF6F7976)
val ExpensoOutlineVariantLight = Color(0xFFBFC9C5)

// Dark Expenso
val ExpensoBackgroundDark = Color(0xFF1A1C1B)
val ExpensoTextDark = Color(0xFFE0E3DF)
val ExpensoPrimaryDark = Color(0xFF6EDBC4)
val ExpensoOnPrimaryDark = Color(0xFF003730)
val ExpensoPrimaryContainerDark = Color(0xFF005046)
val ExpensoOnPrimaryContainerDark = Color(0xFF8FF5E0)
val ExpensoSecondaryDark = Color(0xFFB0CCC5)
val ExpensoSecondaryContainerDark = Color(0xFF324B47)
val ExpensoOnSecondaryContainerDark = Color(0xFFCCE8E2)
val ExpensoSurfaceDark = Color(0xFF1A1C1B)
val ExpensoOnSurfaceDark = Color(0xFFE0E3DF)
val ExpensoOutlineDark = Color(0xFF89938F)
val ExpensoOutlineVariantDark = Color(0xFF3F4946)

// --- PLUM PALETTE ---
// Light
val PlumBackgroundLight = Color(0xFFFFF7FB)
val PlumTextLight = Color(0xFF1F1A1F)
val PlumPrimaryLight = Color(0xFF794F81)
val PlumOnPrimaryLight = Color(0xFFFFFFFF)
val PlumPrimaryContainerLight = Color(0xFFFCD6FF)
val PlumOnPrimaryContainerLight = Color(0xFF5F3768)
val PlumSecondaryLight = Color(0xFF6A596C)
val PlumSecondaryContainerLight = Color(0xFFF3DBF2)
val PlumOnSecondaryContainerLight = Color(0xFF524153)
val PlumSurfaceLight = Color(0xFFFFF7FB)
val PlumOnSurfaceLight = Color(0xFF1F1A1F)
val PlumOutlineLight = Color(0xFF7E747D)
val PlumOutlineVariantLight = Color(0xFFCFC3CD)

// Dark
val PlumBackgroundDark = Color(0xFF161217)
val PlumTextDark = Color(0xFFEAE0E7)
val PlumPrimaryDark = Color(0xFFE8B5EF)
val PlumOnPrimaryDark = Color(0xFF472150)
val PlumPrimaryContainerDark = Color(0xFF5F3768)
val PlumOnPrimaryContainerDark = Color(0xFFFCD6FF)
val PlumSecondaryDark = Color(0xFFD6C0D6)
val PlumSecondaryContainerDark = Color(0xFF524153)
val PlumOnSecondaryContainerDark = Color(0xFFF3DBF2)
val PlumSurfaceDark = Color(0xFF161217)
val PlumOnSurfaceDark = Color(0xFFEAE0E7)
val PlumOutlineDark = Color(0xFF988E97)
val PlumOutlineVariantDark = Color(0xFF4C444C)

// Medium Light
val PlumMediumBackgroundLight = Color(0xFFFFF7FB)
val PlumMediumTextLight = Color(0xFF1F1A1F)
val PlumMediumPrimaryLight = Color(0xFF4D2756)
val PlumMediumOnPrimaryLight = Color(0xFFFFFFFF)
val PlumMediumPrimaryContainerLight = Color(0xFF895D91)
val PlumMediumOnPrimaryContainerLight = Color(0xFFFFFFFF)
val PlumMediumSecondaryLight = Color(0xFF403142)
val PlumMediumSecondaryContainerLight = Color(0xFF7A677B)
val PlumMediumOnSecondaryContainerLight = Color(0xFFFFFFFF)
val PlumMediumSurfaceLight = Color(0xFFFFF7FB)
val PlumMediumOnSurfaceLight = Color(0xFF141014)
val PlumMediumOutlineLight = Color(0xFF585058)
val PlumMediumOutlineVariantLight = Color(0xFF746A73)

// Medium Dark
val PlumMediumBackgroundDark = Color(0xFF161217)
val PlumMediumTextDark = Color(0xFFEAE0E7)
val PlumMediumPrimaryDark = Color(0xFFFACEFF)
val PlumMediumOnPrimaryDark = Color(0xFF3B1545)
val PlumMediumPrimaryContainerDark = Color(0xFFAF81B7)
val PlumMediumOnPrimaryContainerDark = Color(0xFF000000)
val PlumMediumSecondaryDark = Color(0xFFEDD5EC)
val PlumMediumSecondaryContainerDark = Color(0xFF9F8A9F)
val PlumMediumOnSecondaryContainerDark = Color(0xFF000000)
val PlumMediumSurfaceDark = Color(0xFF161217)
val PlumMediumOnSurfaceDark = Color(0xFFFFFFFF)
val PlumMediumOutlineDark = Color(0xFFBAAEB8)
val PlumMediumOutlineVariantDark = Color(0xFF988D96)

// High Light
val PlumHighBackgroundLight = Color(0xFFFFF7FB)
val PlumHighTextLight = Color(0xFF1F1A1F)
val PlumHighPrimaryLight = Color(0xFF421C4C)
val PlumHighOnPrimaryLight = Color(0xFFFFFFFF)
val PlumHighPrimaryContainerLight = Color(0xFF623A6B)
val PlumHighOnPrimaryContainerLight = Color(0xFFFFFFFF)
val PlumHighSecondaryLight = Color(0xFF362738)
val PlumHighSecondaryContainerLight = Color(0xFF544456)
val PlumHighOnSecondaryContainerLight = Color(0xFFFFFFFF)
val PlumHighSurfaceLight = Color(0xFFFFF7FB)
val PlumHighOnSurfaceLight = Color(0xFF000000)
val PlumHighOutlineLight = Color(0xFF312A31)
val PlumHighOutlineVariantLight = Color(0xFF4F474F)

// High Dark
val PlumHighBackgroundDark = Color(0xFF161217)
val PlumHighTextDark = Color(0xFFEAE0E7)
val PlumHighPrimaryDark = Color(0xFFFFEAFE)
val PlumHighOnPrimaryDark = Color(0xFF000000)
val PlumHighPrimaryContainerDark = Color(0xFFE4B2EB)
val PlumHighOnPrimaryContainerDark = Color(0xFF1A0023)
val PlumHighSecondaryDark = Color(0xFFFFEAFE)
val PlumHighSecondaryContainerDark = Color(0xFFD2BCD2)
val PlumHighOnSecondaryContainerDark = Color(0xFF130716)
val PlumHighSurfaceDark = Color(0xFF161217)
val PlumHighOnSurfaceDark = Color(0xFFFFFFFF)
val PlumHighOutlineDark = Color(0xFFFAECF6)
val PlumHighOutlineVariantDark = Color(0xFFCBBFC9)

// Pure Black (Amoled)
val PlumAmoledBackgroundDark = Color(0xFF000000)
val PlumAmoledTextDark = Color(0xFFEAE0E7)
val PlumAmoledPrimaryDark = Color(0xFFE8B5EF)
val PlumAmoledOnPrimaryDark = Color(0xFF472150)
val PlumAmoledPrimaryContainerDark = Color(0xFF5F3768)
val PlumAmoledOnPrimaryContainerDark = Color(0xFFFCD6FF)
val PlumAmoledSecondaryDark = Color(0xFFD6C0D6)
val PlumAmoledSecondaryContainerDark = Color(0xFF524153)
val PlumAmoledOnSecondaryContainerDark = Color(0xFFF3DBF2)
val PlumAmoledSurfaceDark = Color(0xFF000000)
val PlumAmoledOnSurfaceDark = Color(0xFFEAE0E7)
val PlumAmoledOutlineDark = Color(0xFF988E97)
val PlumAmoledOutlineVariantDark = Color(0xFF4C444C)
